service: indexer

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}

functions:
  indexer:
    handler: metadata-indexer.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [EpisodeMetadata, StreamArn]
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - es:ESHttpPost
          - es:ESHttpPut
        Resource: "*"

custom:
  pythonRequirements:
    dockerizePip: non-linux

resources:
  Resources: 
    EpisodeMetadata:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-episode-metadata
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    EpisodeSearch:
      Type: AWS::Elasticsearch::Domain
      Properties:
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
        ElasticsearchVersion: 7.7
